# Generated by Django 4.1.5 on 2023-01-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_phon',
            field=models.CharField(max_length=12, null=True, verbose_name='Номер телефона'),
        ),
    ]
