# Generated by Django 4.1.5 on 2023-01-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Покупки', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.IntegerField(null=True, verbose_name='Покупатель'),
        ),
    ]
