# Generated by Django 4.1.5 on 2023-01-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orders_options_alter_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tranzit',
            field=models.CharField(max_length=30, null=True, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number_phon',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_slug_list',
            field=models.CharField(max_length=900, verbose_name='Покупки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Покупатель'),
        ),
    ]
